apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: BackendTechTrend
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1

  selector:
    matchLabels:
      app: BackendTechTrend

  template:
    metadata:
      labels:
        app: BackendTechTrend
    spec:
      containers:
      - image: shivasurya/techtrends:latest
        name: techtrends
        ports:
          - containerPort: 3111
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
